version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install --exists-action=w --no-cache-dir --use-pep517 -r requirements.txt

sphinx:
  # myst parser emits warnings for links in md files
  # that point to a local folder.
  fail_on_warning: false
