version: 2

python:
  install:
    - requirements: requirements.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

sphinx:
  # myst parser emits warnings for links in md files
  # that point to a local folder.
  fail_on_warning: false
